sudo: required

language: python

env:
  matrix:
    - DEBUG=1
    - DEBUG=0

services:
  - docker

before_script:
  - sed -i "s/^WEBLATE_DEBUG=.*/WEBLATE_DEBUG=$DEBUG/" environment
  - docker-compose build

script:
  - ./test.sh
